#!/bin/bash
echo ">>> Backend asset generation complete and OWL syntax updated. <<<"
echo ""
echo "====================================================================="
echo " ACTION REQUIRED: BROWSER CACHE CLEAR"
echo "====================================================================="
echo "Since the 'KeyNotFoundError' is a client-side JavaScript error,"
echo "your browser may still be holding the old broken asset bundle."
echo ""
echo "1. Open your browser and navigate to: https://erp.airiv.id/web"
echo "2. Perform a HARD REFRESH to fetch the new bundles:"
echo "   - Windows/Linux: Ctrl + F5 or Shift + F5"
echo "   - Mac: Cmd + Shift + R"
echo "3. Click the 'Executive Dashboard' menu."
echo "====================================================================="
