{
    "name": "AIRIV Dashboard Indonesia",
    "version": "18.0.1.0.0",
    "category": "Extra Tools",
    "summary": "Indonesian regional operational intelligence, PPN tax oversight, and logistics monitoring for UMKM.",
    "author": "Riv Cloud Management",
    "website": "https://airiv.id",
    "license": "LGPL-3",
    "price": 0.0,
    "currency": "EUR",
    "depends": ["base", "account", "sale", "stock"],
    "data": ["security/ir.model.access.csv"],
    "installable": True,
    "application": True,
    "auto_install": False,
}